#
# Homelab Machine Monitoring Services
#
# References:
# - https://blog.linuxserver.io/2017/11/25/how-to-monitor-your-server-using-grafana-influxdb-and-telegraf/
# - https://grafana.com/grafana/dashboards/893
#

version: "2.4"
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: monitor-prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
      - type: volume
        source: prometheus_data_volume
        target: /prometheus
    restart: unless-stopped
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'  
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=neuk.davidmuir.co.uk
      #- GF_SMTP_ENABLED=true
      #- GF_SMTP_HOST=smtp.gmail.com:587
      #- GF_SMTP_USER=myadrress@gmail.com
      #- GF_SMTP_PASSWORD=mypassword
      #- GF_SMTP_FROM_ADDRESS=d.h.muir@gmail.com

volumes:
  prometheus_data_volume:
    driver_opts:
      type: "nfs"
      o: "addr=neuknas,nolock,soft,rw"
      device: ":/mnt/dpool2/docker_service_monitor/prometheus"

