#
# Homelab Portainer Services
#

version: "2.4"
services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_data_volume:
    driver_opts:
      type: "nfs"
      o: "addr=neuknas,nolock,soft,rw"
      device: ":/mnt/dpool2/docker_service_monitor/prometheus"

