# escape=`

#
# Dockerfile for Microsoft Build Tools 2019 Image
# dhm@davidmuir.co.uk
#

ARG FROM_IMAGE=mcr.microsoft.com/windows/servercore:2004
FROM ${FROM_IMAGE}

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Install Build Tools with the Microsoft.VisualStudio.Workload.AzureBuildTools workload, excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
	--installPath C:\BuildTools `
	--includeRecommended `
	--add Microsoft.VisualStudio.Workload.AzureBuildTools `
	--add Microsoft.VisualStudio.Workload.DataBuildTools `
	--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools `
	--add Microsoft.VisualStudio.Workload.MSBuildTools `
	--add Microsoft.VisualStudio.Workload.NetCoreBuildTools `
	--add Microsoft.VisualStudio.Workload.OfficeBuildTools `
	--add Microsoft.VisualStudio.Workload.UniversalBuildTools `
	--add Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools `
	--add Microsoft.VisualStudio.Workload.WebBuildTools `
	--add Microsoft.Net.Component.3.5.DeveloperTools `
	--add Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools `
	--add Microsoft.Net.ComponentGroup.4.7.2.DeveloperTools `
	--add Microsoft.Net.ComponentGroup.TargetingPacks.Common `
	--add Microsoft.VisualStudio.Component.TestTools.BuildTools `
	--add Microsoft.VisualStudio.Workload.VCTools `
	--add Microsoft.VisualStudio.Component.VC.CoreBuildTools `
	--add Microsoft.VisualStudio.Component.VC.140 `
	--add Microsoft.VisualStudio.Component.VC.ATL `
	--add Microsoft.VisualStudio.Component.VC.ATLMFC `
	--add Microsoft.VisualStudio.Component.VC.CLI.Support `
	--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
	--add Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop `
	--add Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop `
	--add Microsoft.VisualStudio.Component.Windows10SDK.17134 `
	--add Microsoft.VisualStudio.Component.Windows10SDK.17763 `
	--add Microsoft.VisualStudio.Component.WinXP `
	--add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP `
	--add Microsoft.VisualStudio.Workload.NodeBuildTools `
	--add Microsoft.VisualStudio.Component.TypeScript.2.8 `
	|| IF "%ERRORLEVEL%"=="3010" EXIT 0

# Define the entry point for the docker container.
# This entry point starts the developer command prompt and launches the PowerShell shell.
ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
